config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


	root 'pages#home'

  resources :articles

  get 'signup',to: 'users#new'
  resources :users, except: [:new]


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true, length: { minimum: 3, maximum: 50}
	validates :description, presence: true, length: { minimum: 10, maximum: 300}
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles
	before_save { self.email = email.downcase }
	validates :username, presence: true, uniqueness: {case_sensitive: false},
	length: { minimum:3, maximum:25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, uniqueness: { case_sensitive: false},
	length: { maximum: 105},
	format: { with: VALID_EMAIL_REGEX }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def edit
	end

	def create
		#render plain: params[:article].inspect
		#debugger
		@article = Article.new(article_params)
		@article.user = User.first
		# @article.save
		if @article.save
			# do something
			flash[:success] = "Article was created"
			redirect_to article_path(@article)
		else
			render 'new'
		end
		# redirect_to article_path(@article)
	end
   
  def update
  	#render plain: params[:article].inspect
		# @article.save
		if @article.update(article_params)
			# do something
			flash[:success] = "Article was updated"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
		# redirect_to article_path(@article)
	end

	def show
	end

	def destroy
		@article.destroy

		flash[:danger] = "Article deleted"
		redirect_to articles_path
	end

  private
  def article_params
  	params.require(:article).permit(:title, :description)
  end	
  
  private
  def set_article
  	@article = Article.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
	def about
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		render 'new'
		#debugger
	end

	def destroy

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Welcome to the E36 Blog #{@user.username}"
			redirect_to articles_path
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:success] = "Account updated!"
			redirect_to articles_path

		else	
			render 'edit'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def index
		@users = User.all
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
	end
	def about
	end
	def login
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = { size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
	<div class="form">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="card card-lg">
				<div class="article-title">
				<%= link_to article.title, article_path(article) %>
				</div>
			<div class="article-body">
				<%= truncate(article.description, length: 100) %>
				<div class="article-meta-details">
				<small>Created by: <%= article.user.username if article.user %>
					<%= time_ago_in_words(article.created_at) %> ago,
					Last Updated: <%= time_ago_in_words(article.updated_at) %> ago
				</small>
			</div>
			</div>
				<div class="article-actions">
				<%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
				<%= link_to "Delete this article", article_path(article), method: :delete,
										    data:{confirm: "Are you sure you want to delete the article?"},
										    class: "btn btn-xs btn-danger" %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class='form-group'>
	<!-- <div class="col-xs-12"> -->
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<!-- <div class="col-sm-2 col-form-label"> -->
	  			<%= f.label :title %>
	  		</div>
	  		<div class="form-group">
	  			<!-- <div class="col-sm-10"> -->
	  			<%= f.text_field :title, class:"form-control ", placeholder: "Title of Article", autofocus: true %>
				<!-- </div> -->
			</div>
			<div class="form-group">
				<!-- <div class="col-sm-2 col-form-label"> -->
	  				<%= f.label :description %>
	  		</div>
	  		<div class="form-group">
	  			<!-- <div class="col-sm-10"> -->
	  				<%= f.text_area :description, rows: 10, class:"form-control", placeholder: "Body of Article", autofocus: true %>
	  			<!-- </div> -->
	  		</div>
	  		<div class="form-group">
	  			<!-- <div class="col-sm-offset col-sm-10"> -->
					<%= f.submit class: 'btn btn-primary' %>
			</div>
			<!-- </div> -->
		<% end %>
	 	<div class="col-xs-4">
			<%= link_to "Cancel request and return back to article listing", articles_path %>
		</div>
  	<!-- </div> -->
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit the selected article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<div align="center">
	<%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
	<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>

<!-- Add in partial form contents (_form.html.erb) -->
<!-- If the form is in another path ref something like shared/form  -->
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"> Title: <%= @article.title %></h2>

<div class="card bg-light col-xs-8 offset-xs-2">
	<% if @article.user %>
	<ul class="listing">
		<div align="center" class="form-group">
			<div class="col-md-4 col-md-offset-4">
				<li>Created by:</li>
				<li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
				<li class="article-title">
					<%= link_to @article.user.username, user_path(@article.user) %>
				</li>
				<li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
			</div>
		</div>
	</ul>
	<% end %>
	<h4 class="center description"><strong>Description:</strong></h4>
	<hr>
	<%= simple_format(@article.description) %>
	<div class="article-actions">
		<%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
		<%= link_to "Delete this article", article_path(@article), method: :delete,
										    data:{confirm: "Are you sure you want to delete the article?"},
										    class: "btn btn-xs btn-danger" %>
		<%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; <a href="https://codyellington.com">The Tester</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to "About", root_path %></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="form">
	<!-- <div class="col-xs-10 col-xs-offset-1"> -->
		<% flash.each do |name, msg| %>
		<div class='alert alert-<%="#{name}" %>'>
			<a href="#" class="close" data-dismiss="alert">&#215;</a>
			<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
		</div>
	<% end %>
	<!-- </div> -->
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <%= link_to "E36 Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-link"><%= link_to "Articles", articles_path %></li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" <%= link_to "New Article", new_article_path %></a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E36-Blog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>My first website!</title>
	<link rel="stylesheet" type="text/css" href="style.css">
	<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
</head>
<body>
	<header>
		<nav>
			<ul>
				<%= link_to 'Home', root_path %>
				<li>About</li>
				<%= link_to 'Login', login_path %>
			</ul>
		</nav>
	</header>
	<section>
		<h2>About</h2>
		<img src="http://www.gradywhite.com/media/4841/ec.jpg" width="250" height="250">
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</section>
	<footer>This Website made with love</footer>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<div class="center jumbotron">
	<h1>E36 BLOG</h1>
	<%= link_to 'Sign up now', '#', class: "btn btn-primary btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="form-group">
<!-- 		<div class="col-xs-8 col-xs-offset-2"> -->
			<div class="card text-white bg-danger mb-3 style="max-width: 18rem;">
				<div class="card-heading">
					<h2 class="card-title">
						<%= pluralize(obj.errors.count, "error") %>
						prohibited this article from saving:
					</h2>
					<div class="card-body">
						<ul>
							<% obj.errors.full_messages.each do |msg| %>
  							  <li><%= msg %></li>
  							<% end %>
  						</ul>
  					</div>
  				</div>
  			</div>
<!--   		</div> -->
  	</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='form-group'>
	<!-- <div class="col-xs-12"> -->
		<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<!-- <div class="col-sm-2 col-form-label"> -->
	  			<%= f.label :username %>
	  		</div>
	  		<div class="form-group">
	  			<!-- <div class="col-sm-10"> -->
	  			<%= f.text_field :username, class:"form-control ", placeholder: "Enter Username", autofocus: true %>
				<!-- </div> -->
			</div>
			<div class="form-group">
				<!-- <div class="col-sm-2 col-form-label"> -->
	  				<%= f.label :email %>
	  		</div>
	  		<div class="form-group">
	  			<!-- <div class="col-sm-10"> -->
	  				<%= f.email_field :email, class:"form-control", placeholder: "Enter Email", autofocus: true %>
	  			<!-- </div> -->
	  		</div>
	  		<div class="form-group">
	  			<!-- <div class="col-sm-10"> -->
	  				<%= f.label :password %>
	  			<!-- </div> -->
	  		</div>
	  		<div class="form-group">
	  			<!-- <div class="col-sm-10"> -->
	  				<%= f.password_field :password, class:"form-control", placeholder: "Enter Password", autofocus: true %>
	  			<!-- </div> -->
	  		</div>
	  		<div class="form-group">
	  			<!-- <div class="col-sm-offset col-sm-10"> -->
					<%= f.submit(@user.new_record? ? "Sign up" : "Update your account", class: 'btn btn-primary') %>
			</div>
			<!-- </div> -->
		<% end %>
	 	<div class="col-xs-4">
			<%= link_to "Cancel request and return back to article listing", articles_path %>
		</div>
  	<!-- </div> -->
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All E36 Bloggers</h1>

<% @users.each do |user| %>

	<ul class="listing">
		<div align="center" class="form-group">
			<div class="card col-md-4 col-md-offset-4">
				<li><%= link_to gravatar_for(user), user_path(user) %></li>
				<li class="article-title">
					<%= link_to user.username, user_path(user) %>
				</li>
				<li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
			</div>
		</div>
	</ul>
<% end %> 

app/views/users/new.html.erb
<h1 align="center">Sign up for E36 Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div class="form-group">
	<div align="center" class="form-group">
	<%= gravatar_for @user, size: 150 %>
	</div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>

<%= render 'articles/article', obj: @user.articles %>

app/views/welcome/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>My first website!</title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<button class="btn btn-primary">Default</button>
	<header>
		<nav>
			<ul>
				<li>Home</li>
				<%= link_to 'About', about_path %>
				<%= link_to 'Login', login_path %>
			</ul>
		</nav>
	</header>
	<section>
		<h2>Home</h2>
		<div id="div1">
        <p class="webtext active">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		<p class="webtext">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		<p class="webtext">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</div>
	<div id="div2">
        <p class="webtext active">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		<p class="webtext">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		<p class="webtext">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</div>	
	</section>
</body>
</html>